version: '3.8'
services:
  user_db:
    image: postgres:latest
    container_name: yourkasa_user_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - yourkasa_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: yourkasa_user_service
    env_file: .env
    environment:
      - DB_HOST=user_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - user_db
    networks:
      - yourkasa_network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: yourkasa_auth_service
    env_file: .env
    environment:
      - DB_HOST=user_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "8081:8081"
    depends_on:
      - user_db
    networks:
      - yourkasa_network

volumes:
  user_db_data:
    name: yourkasa_user_db_data

networks:
  yourkasa_network:
    name: yourkasa_network
    driver: bridge
